import {
  Entity,
  BaseEntity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne
} from "typeorm";

// Models
import { User } from "./User";

enum ENUMLanguage {
  A1 = "Español",
  A2 = "Inglés",
  A3 = "Portugués",
  A4 = "Ruso",
  A5 = "Árabe",
  A6 = "Chino",
  A7 = "Francés",
  A8 = "Alemán",
  A9 = "Abjaso",
  B1 = "Afar",
  B2 = "Afrikaans",
  B3 = "Aimara",
  B4 = "Akano",
  B5 = "Albanés",
  B6 = "Amárico",
  B7 = "Aragonés",
  B8 = "Armenio",
  B9 = "Asamés",
  C1 = "Avar",
  C2 = "Avéstico",
  C3 = "Azerí",
  C4 = "Bambara",
  C5 = "Baskir",
  C6 = "Bengalí",
  C7 = "Bhojpurí",
  C8 = "Bielorruso",
  C9 = "Birmano",
  D1 = "Bislama",
  D2 = "Bosnio",
  D3 = "Bretón",
  D4 = "Búlgaro",
  D5 = "Cachemiro",
  D6 = "Camboyano",
  D7 = "Canarés",
  D8 = "Catalán",
  D9 = "Chamorro",
  E1 = "Checheno",
  E2 = "Checo",
  E3 = "Chichewa",
  E4 = "Chuan",
  E5 = "Chuvasio",
  E6 = "Cingalés",
  E7 = "Coreano",
  E8 = "Corso",
  E9 = "Cree",
  F1 = "Croata",
  F2 = "Córnico",
  F3 = "Danés",
  F4 = "Dzongkha",
  F5 = "Eslavo",
  F6 = "Eslovaco",
  F7 = "Esloveno",
  F8 = "Esperanto",
  F9 = "Estonio",
  G1 = "Euskera",
  G2 = "Ewe",
  G3 = "Feroés",
  G4 = "Finés",
  G5 = "Fiyiano",
  G6 = "Frisón",
  G7 = "Fula",
  G8 = "Gallego",
  G9 = "Galés",
  H1 = "Gaélico",
  H2 = "Gaélico Escocés",
  H3 = "Georgiano",
  H4 = "Griego",
  H5 = "Groenlandés",
  H6 = "Guaraní",
  H7 = "Guyaratí",
  H8 = "Haitiano",
  H9 = "Hausa",
  I1 = "Hebreo",
  I2 = "Herero",
  I3 = "Hindú",
  I4 = "Hiri Motu",
  I5 = "Húngaro",
  I6 = "Ido",
  I7 = "Igbo",
  I8 = "Indonesio",
  I9 = "Interlingua",
  J1 = "Inuktitut",
  J2 = "Inupiaq",
  J3 = "Islandés",
  J4 = "Italiano",
  J5 = "Japonés",
  J6 = "Javanés",
  J7 = "Kanuri",
  J8 = "Kazajo",
  J9 = "Kikuyu",
  K1 = "Kirguís",
  K2 = "Kirundi",
  K3 = "Komi",
  K4 = "Kongo",
  K5 = "Kuanyama",
  K6 = "Kurdo",
  K7 = "Lao",
  K8 = "Latín",
  K9 = "Letón",
  L1 = "Limburgués",
  L2 = "Lingala",
  L3 = "LituanoLuba-Katanga",
  L4 = "Luganda",
  L5 = "Luxemburgués",
  L6 = "Macedonio",
  L7 = "Malayalam",
  L8 = "Malayo",
  L9 = "Maldivo",
  M1 = "Malgache",
  M2 = "Maltés",
  M3 = "Manés",
  M4 = "Maorí",
  M5 = "Mapugundun",
  M6 = "Maratí",
  M7 = "Marshalés",
  M8 = "Mongol",
  M9 = "Nauruano",
  N1 = "Navajo",
  N2 = "Ndebele Del Norte",
  N3 = "Ndebele Del Sur",
  N4 = "Ndonga",
  N5 = "Neerlandés",
  N6 = "Nepalí",
  N7 = "Noruego",
  N8 = "Noruego Bokmål",
  N9 = "Nynorsk",
  O1 = "Occidental",
  O2 = "Occitano",
  O3 = "Ojibwa",
  O4 = "Oriya",
  O5 = "Oromo",
  O6 = "Osético",
  O7 = "Pali",
  O8 = "Panyabí",
  O9 = "Pastú",
  P1 = "Persa",
  P2 = "Polaco",
  P3 = "Quechua",
  P4 = "Romanche",
  P5 = "Ruandés",
  P6 = "Rumano",
  P7 = "Sami Septentrional",
  P8 = "Samoano",
  P9 = "Sango",
  Q1 = "Sardo",
  Q2 = "Serbio",
  Q3 = "Sesotho",
  Q4 = "Setsuana",
  Q5 = "Shona",
  Q6 = "Sindhi",
  Q7 = "Somalí",
  Q8 = "Suajili",
  Q9 = "Suazi",
  R1 = "Sueco",
  R2 = "Sundanés",
  R3 = "Sánscrito",
  R4 = "Tagalo",
  R5 = "Tahitiano",
  R6 = "Tailandés",
  R7 = "Tamil",
  R8 = "Tayiko",
  R9 = "Telugú",
  S1 = "Tibetano",
  S2 = "Tigriña",
  S3 = "Tongano",
  S4 = "Tsonga",
  S5 = "Turco",
  S6 = "Turcomano",
  S7 = "Twi",
  S8 = "Tártaro",
  S9 = "Ucraniano",
  T1 = "Uigur",
  T2 = "Urdu",
  T3 = "Uzbeko",
  T4 = "Valón",
  T5 = "Venda",
  T6 = "Vietnamita",
  T7 = "Volapük",
  T8 = "Wolof",
  T9 = "Xhosa",
  U1 = "Yi De Sichuán",
  U2 = "Yoruba",
  U3 = "Yídish",
  U4 = "Zulú"
}

enum ENUMLanguageLevel {
  A1 = "Muy básico",
  A2 = "Básico",
  A3 = "Intermedio",
  A4 = "Avanzado",
  A5 = "Nativo"
}

@Entity()
export class Languages extends BaseEntity {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column("enum", { enum: ENUMLanguage })
  language: string;

  @Column("enum", { enum: ENUMLanguageLevel })
  level: string;

  @ManyToOne(_ => User, user => user.language)
  user: User;
}
