FROM node:8.12.0-alpine

ENV NODE_ENV production

WORKDIR /usr/app

COPY ../../server/package.json .

RUN yarn install --production=true --silent

RUN yarn run build

COPY ../../server/dist ./server/dist
COPY ../../server/ormconfig.json .

EXPOSE 4000

CMD ["yarn", "prod"]

USER node